MojOsInternal.h: update for glibc-2.34
* as https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html says:
  * The function pthread_yield has been deprecated; programs should use
    the equivalent standard function sched_yield instead.

  it doesn't cause db8 build itself to fail, but some components which use
  MojOsInternal.h (like keymanager) also use -Werror which causes:
  recipe-sysroot/usr/include/mojodb/core/internal/MojOsInternal.h:345:38: error: 'int pthread_yield()' is deprecated: pthread_yield is deprecated, use sched_yield instead [-Werror=deprecated-declarations]
  |   345 |         return (MojErr) pthread_yield();
  |       |                         ~~~~~~~~~~~~~^~

Signed-off-by: Martin Jansa <martin.jansa@lge.com>
Change-Id: I2fb0e0a595bd83147d2b793a804df8a515d43fbd